### ISSUE TITLE
Bug Report: Connecting to server via Local IP in certain configurations causes timed out error, kick, or crash

### ISSUE THREAD

**Issue by teconmoon** [GameCubeOnline/MKDDOnline#2]
## Describe the bug
When trying to connect to a locally-hosted server using a local IP address, the connection can fail with a few different variations:

1. The connection page will say **Timed Out**.
2. The connection will proceed, and then kick you to the title screen.
3. The connection will proceed, and then freeze on a screen that says "A race is already in progress, please wait..."

On the latter two errors, the server will spit the following in the output:
```
User DoubleDashOnlineV005 Joined.
java.lang.ArrayIndexOutOfBoundsException: Index 83 out of bounds for length 8
        at root.GameReader.run(GameReader.java:63)
        at root.ServerUser.main(ServerUser.java:534)
        at root.ServerUser.run(ServerUser.java:424)
DoubleDashOnlineV005 tried to output a malformed packet
```
In this error, it always says that the user is DoubleDashOnlineV005 regardless of the client's entered name.

A few other notes:
- The server was hosted on Windows, tested with both Java 8 and Java 21.
- The same issue occurs with both the posted release (0.0.5a) and the decomp build.
- The client was a Nintendo GameCube connecting using an ETH2GC Adapter.
- Trying to connect to the same server via a port-forwarded public IP instead of a local IP, oddly enough, worked without any issues.
- I tried connecting to the local server IP with Dolphin using the HLE BBA adapter, and was not able to duplicate the issue.

Untested scenarios:
- Dolphin TAP BBA
- Nintendont BBA Emulation on Wii or Wii U
- GameCube /w Official BBA

## To Reproduce
1. Host a server locally
2. Try to connect to your local server's IP
3. Experience the issues stated above

## Expected behavior
The console should connect.

**Comment by rpf16rj** [comment]
I had this issue on v0.0.6 from windows as server.
